server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.0.21:3306/was?useUnicode=true&characterEncoding=UTF8
    userName: root
    password: 123456
  application:
    name: fq-ltd-was-backstage
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      cache: false


# Mybatis配置
mybatis:
    basepackage: com.fq.fqltdwasbackstage.mapper
    xmlLocations: classpath:mapper/**/*.xml
